#!/usr/bin/env node
// Generates src/icons/icons.ts from the lucide-react package already present
// in the workspace (vendored data: @forge/ui keeps zero runtime deps beyond
// react). Follows alias re-exports (e.g. help-circle -> circle-help) and
// extracts each icon's __iconNode array. Rerun after editing NAMES:
//
//     node packages/ui/scripts/generate-icons.mjs
//
// Icon data (c) Lucide Contributors, ISC license (see the attribution header
// written into icons.ts).
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(pkgRoot, "..", "..");

// Locate lucide-react's esm icon directory through .pnpm (lucide-react is a
// dependency of @forge/editor, not of this package).
const pnpmDir = join(repoRoot, "node_modules", ".pnpm");
const lucideEntry = readdirSync(pnpmDir).find((d) => d.startsWith("lucide-react@"));
if (!lucideEntry) {
  console.error("lucide-react not found under node_modules/.pnpm");
  process.exit(1);
}
const iconsDir = join(pnpmDir, lucideEntry, "node_modules", "lucide-react", "dist", "esm", "icons");
const lucideVersion = lucideEntry.match(/lucide-react@([\d.]+)/)?.[1] ?? "unknown";

// Curated set: every name the editor chrome imports from lucide today, plus
// system basics so product work never starts by adding an icon.
const NAMES = [
  // navigation and chevrons
  "arrow-down", "arrow-left", "arrow-right", "arrow-up",
  "chevron-down", "chevron-left", "chevron-right", "chevron-up",
  "chevrons-up-down", "external-link", "home", "menu",
  "more-horizontal", "more-vertical", "panel-left",
  // actions
  "check", "x", "plus", "minus", "copy", "download", "upload", "upload-cloud",
  "pencil", "trash-2", "search", "settings", "sliders-horizontal", "filter",
  "refresh-cw", "undo-2", "redo-2", "zoom-in", "zoom-out", "expand",
  "grip-vertical", "mouse-pointer-click", "eye", "eye-off", "lock", "lock-open",
  "log-out",
  // status and messaging
  "info", "help-circle", "alert-circle", "triangle-alert", "circle-check",
  "check-square", "square", "flag", "star", "heart", "bookmark", "bell",
  // media
  "image", "video", "music", "volume-2", "play", "pause", "captions",
  "clapperboard", "camera", "mic",
  // objects
  "file", "file-text", "folder", "link", "paperclip", "user", "users",
  "calendar", "clock", "book-open", "layers", "package", "git-branch",
  // editorial and layout
  "bold", "italic", "strikethrough", "underline", "heading-1", "heading-2",
  "heading-3", "list", "list-ordered", "list-collapse", "text-quote", "quote",
  "type", "code", "table", "layout-grid", "columns-3", "grid-3x3", "palette",
  "bar-chart-3", "pie-chart",
  // devices and mode
  "monitor", "tablet", "smartphone", "languages", "sun", "moon",
];

const nodeRe = /const __iconNode = (\[[\s\S]*?\]);\s*\n/;
const aliasRe = /export \{ default \} from '\.\/([a-z0-9-]+)\.js';/;

function readIcon(name, hops = 0) {
  if (hops > 4) throw new Error(`alias loop at ${name}`);
  const file = join(iconsDir, `${name}.js`);
  if (!existsSync(file)) throw new Error(`no lucide icon "${name}"`);
  const src = readFileSync(file, "utf8");
  const alias = src.match(aliasRe);
  if (alias) return readIcon(alias[1], hops + 1);
  const m = src.match(nodeRe);
  if (!m) throw new Error(`no __iconNode in ${name}.js`);
  // The array literal is JSON except for unquoted keys; lucide emits
  // ["tag", { key: "value", ... }] pairs with double-quoted values already.
  // eslint-disable-next-line no-new-func
  const node = new Function(`return ${m[1]};`)();
  return node.map(([tag, attrs]) => {
    const { key, ...rest } = attrs; // react list key is irrelevant here
    return [tag, rest];
  });
}

const failures = [];
const entries = [];
for (const name of [...NAMES].sort()) {
  try {
    entries.push([name, readIcon(name)]);
  } catch (error) {
    failures.push(`${name}: ${error.message}`);
  }
}
if (failures.length > 0) {
  console.error("icon extraction failed:\n  " + failures.join("\n  "));
  process.exit(1);
}

const body = entries
  .map(([name, node]) => `  "${name}": ${JSON.stringify(node)},`)
  .join("\n");

const out = `// GENERATED by scripts/generate-icons.mjs. Do not edit by hand.
// Icon geometry vendored from lucide-react v${lucideVersion}.
//
// Lucide License (ISC)
// Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as
// part of Feather (MIT). All other copyright (c) for Lucide are held by
// Lucide Contributors 2022. Permission to use, copy, modify, and/or
// distribute this software for any purpose with or without fee is hereby
// granted, provided that the above copyright notice and this permission
// notice appear in all copies.
// https://lucide.dev/license

/** One SVG child: [tag, attributes]. 24x24 grid, stroke-based. */
export type IconNode = ReadonlyArray<
  readonly [string, Readonly<Record<string, string | number>>]
>;

export const iconData = {
${body}
} as const satisfies Record<string, IconNode>;

export type IconName = keyof typeof iconData;

export const iconNames = Object.keys(iconData) as IconName[];
`;

writeFileSync(join(pkgRoot, "src", "icons", "icons.ts"), out);
console.log(`icons.ts generated: ${entries.length} icons from lucide-react v${lucideVersion}`);
