// GENERATED by src/tokens/build.ts from anvil.tokens.json. Do not edit.
// Resolved token values for programmatic use (canvas, email, native).
// CSS consumers should use the --an-* custom properties from anvil.css.
export const anvilTokens = {
  "color": {
    "cobalt": {
      "50": "#eef4fe",
      "100": "#d9e6fd",
      "200": "#b6cdfb",
      "300": "#8badf7",
      "400": "#5c88f0",
      "500": "#3366e6",
      "600": "#2451d4",
      "700": "#1d41b0",
      "800": "#19368c",
      "900": "#162c6e",
      "950": "#0e1b46"
    },
    "neutral": {
      "0": "#ffffff",
      "50": "#f6f7f9",
      "100": "#eceef2",
      "200": "#dfe2e8",
      "300": "#c9cdd6",
      "400": "#9aa1ad",
      "500": "#6e7683",
      "600": "#545b67",
      "700": "#3e434e",
      "800": "#2b2f38",
      "900": "#1d2026",
      "950": "#14161b",
      "1000": "#0b0c0f"
    },
    "ember": {
      "50": "#fef7ec",
      "100": "#fdecd3",
      "200": "#fad9a5",
      "300": "#f6bf6b",
      "400": "#f0a03a",
      "500": "#e28417",
      "600": "#c2690e",
      "700": "#9c4f0c",
      "800": "#7c3d10",
      "900": "#66320f",
      "950": "#3d1c08"
    },
    "danger": {
      "50": "#fdeeed",
      "100": "#fbdcd9",
      "200": "#f5b7b1",
      "300": "#ec8b82",
      "400": "#e05e53",
      "500": "#cf3a2e",
      "600": "#b02b21",
      "700": "#8e221b",
      "800": "#711d18",
      "900": "#5c1a16",
      "950": "#380e0c"
    },
    "success": {
      "50": "#ecf8f0",
      "100": "#d5f0de",
      "200": "#aae0bf",
      "300": "#74cb98",
      "400": "#41b273",
      "500": "#219653",
      "600": "#177a43",
      "700": "#146137",
      "800": "#124d2e",
      "900": "#103f27",
      "950": "#082517"
    },
    "warn": {
      "50": "#fef8e7",
      "100": "#fdefc4",
      "200": "#fadd8a",
      "300": "#f4c44f",
      "400": "#eaa823",
      "500": "#d18a0f",
      "600": "#ab6c0a",
      "700": "#86520b",
      "800": "#6a400e",
      "900": "#57350e",
      "950": "#332006"
    },
    "info": {
      "50": "#ebf7fb",
      "100": "#d2edf6",
      "200": "#a4dbec",
      "300": "#6cc2dd",
      "400": "#38a5c8",
      "500": "#1c87ab",
      "600": "#146c8c",
      "700": "#125670",
      "800": "#114559",
      "900": "#0f3949",
      "950": "#08222c"
    }
  },
  "space": {
    "0": "0rem",
    "2": "0.125rem",
    "4": "0.25rem",
    "6": "0.375rem",
    "8": "0.5rem",
    "12": "0.75rem",
    "16": "1rem",
    "20": "1.25rem",
    "24": "1.5rem",
    "32": "2rem",
    "40": "2.5rem",
    "48": "3rem",
    "64": "4rem"
  },
  "font": {
    "family": {
      "sans": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "mono": "\"JetBrains Mono\", SFMono-Regular, Menlo, Consolas, monospace"
    },
    "weight": {
      "regular": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700"
    },
    "size": {
      "12": "0.75rem",
      "13": "0.8125rem",
      "14": "0.875rem",
      "16": "1rem",
      "18": "1.125rem",
      "20": "1.25rem",
      "22": "1.375rem",
      "24": "1.5rem",
      "28": "1.75rem",
      "32": "2rem",
      "40": "2.5rem"
    },
    "line": {
      "12": "1.125rem",
      "13": "1.125rem",
      "14": "1.25rem",
      "16": "1.5rem",
      "18": "1.75rem",
      "20": "1.75rem",
      "22": "1.875rem",
      "24": "2rem",
      "28": "2.25rem",
      "32": "2.5rem",
      "40": "3rem"
    },
    "tracking": {
      "tight": "-0.01em",
      "normal": "0em"
    }
  },
  "icon": {
    "size": {
      "16": "16px",
      "20": "20px",
      "24": "24px"
    },
    "stroke": {
      "regular": "2"
    }
  },
  "radius": {
    "xs": "2px",
    "sm": "4px",
    "md": "6px",
    "lg": "10px",
    "xl": "16px",
    "full": "999px"
  },
  "elevation": {
    "0": "0px 0px 0px 1px #14161b0f",
    "1": "0px 0px 0px 1px #14161b0d, 0px 1px 2px 0px #14161b12, 0px 2px 6px 0px #14161b0d",
    "2": "0px 0px 0px 1px #14161b0d, 0px 2px 4px 0px #14161b14, 0px 4px 12px 0px #14161b0f",
    "3": "0px 0px 0px 1px #14161b0a, 0px 4px 8px 0px #14161b17, 0px 8px 24px 0px #14161b14",
    "4": "0px 0px 0px 1px #14161b0a, 0px 8px 16px 0px #14161b1a, 0px 16px 48px 0px #14161b1f"
  },
  "bevel": {
    "highlight": "inset 0px 1px 0px 0px #ffffff24",
    "edge": "inset 0px -1px 0px 0px #14161b2e"
  },
  "duration": {
    "80": "80ms",
    "120": "120ms",
    "160": "160ms",
    "200": "200ms",
    "280": "280ms"
  },
  "ease": {
    "standard": "cubic-bezier(0.2, 0, 0.2, 1)",
    "enter": "cubic-bezier(0.1, 0.8, 0.2, 1)",
    "exit": "cubic-bezier(0.4, 0, 1, 1)",
    "spring": "cubic-bezier(0.3, 1.4, 0.4, 1)"
  },
  "z": {
    "base": "0",
    "raised": "10",
    "sticky": "100",
    "overlay": "700",
    "modal": "800",
    "toast": "900"
  },
  "type": {
    "displayLarge": {
      "fontFamily": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSize": "2.5rem",
      "lineHeight": "3rem",
      "fontWeight": 700,
      "letterSpacing": "-0.02em"
    },
    "display": {
      "fontFamily": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSize": "2rem",
      "lineHeight": "2.5rem",
      "fontWeight": 700,
      "letterSpacing": "-0.02em"
    },
    "headingLarge": {
      "fontFamily": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSize": "1.5rem",
      "lineHeight": "2rem",
      "fontWeight": 600,
      "letterSpacing": "-0.015em"
    },
    "heading": {
      "fontFamily": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSize": "1.25rem",
      "lineHeight": "1.75rem",
      "fontWeight": 600,
      "letterSpacing": "-0.01em"
    },
    "headingSmall": {
      "fontFamily": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "fontWeight": 600,
      "letterSpacing": "-0.005em"
    },
    "labelLarge": {
      "fontFamily": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "fontWeight": 500,
      "letterSpacing": "0em"
    },
    "label": {
      "fontFamily": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSize": "0.875rem",
      "lineHeight": "1.25rem",
      "fontWeight": 500,
      "letterSpacing": "0em"
    },
    "labelSmall": {
      "fontFamily": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSize": "0.8125rem",
      "lineHeight": "1.125rem",
      "fontWeight": 500,
      "letterSpacing": "0.01em"
    },
    "paragraphLarge": {
      "fontFamily": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSize": "1.125rem",
      "lineHeight": "1.75rem",
      "fontWeight": 400,
      "letterSpacing": "0em"
    },
    "paragraph": {
      "fontFamily": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "fontWeight": 400,
      "letterSpacing": "0em"
    },
    "paragraphSmall": {
      "fontFamily": "\"Geist Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSize": "0.875rem",
      "lineHeight": "1.25rem",
      "fontWeight": 400,
      "letterSpacing": "0em"
    },
    "mono": {
      "fontFamily": "\"JetBrains Mono\", SFMono-Regular, Menlo, Consolas, monospace",
      "fontSize": "0.8125rem",
      "lineHeight": "1.25rem",
      "fontWeight": 400,
      "letterSpacing": "0em"
    }
  },
  "semantic": {
    "light": {
      "surface-sunken": "#eceef2",
      "surface-base": "#f6f7f9",
      "surface-raised": "#ffffff",
      "surface-overlay": "#ffffff",
      "text-primary": "#1d2026",
      "text-secondary": "#545b67",
      "text-muted": "#6e7683",
      "text-inverse": "#ffffff",
      "interactive-idle": "#2451d4",
      "interactive-hover": "#1d41b0",
      "interactive-active": "#19368c",
      "interactive-selected": "#eef4fe",
      "accent": "#e28417",
      "accent-strong": "#c2690e",
      "accent-soft": "#fdecd3",
      "border-subtle": "#dfe2e8",
      "border-strong": "#c9cdd6",
      "focus-ring-color": "#3366e6",
      "focus-ring": "0 0 0 2px var(--an-surface-base), 0 0 0 4px var(--an-focus-ring-color)",
      "focus-glow": "0 0 0 3px color-mix(in srgb, var(--an-focus-ring-color) 18%, transparent)",
      "focus-glow-danger": "0 0 0 3px color-mix(in srgb, var(--an-status-danger-solid) 18%, transparent)",
      "brand-gradient": "linear-gradient(135deg, var(--an-color-cobalt-500), var(--an-color-cobalt-700))",
      "accent-gradient": "linear-gradient(135deg, var(--an-color-ember-400), var(--an-color-ember-600))",
      "backdrop": "rgba(11, 12, 15, 0.4)",
      "status-success-fg": "#177a43",
      "status-success-bg": "#ecf8f0",
      "status-success-border": "#aae0bf",
      "status-success-solid": "#219653",
      "status-warn-fg": "#86520b",
      "status-warn-bg": "#fef8e7",
      "status-warn-border": "#fadd8a",
      "status-warn-solid": "#d18a0f",
      "status-danger-fg": "#b02b21",
      "status-danger-bg": "#fdeeed",
      "status-danger-border": "#f5b7b1",
      "status-danger-solid": "#cf3a2e",
      "status-info-fg": "#146c8c",
      "status-info-bg": "#ebf7fb",
      "status-info-border": "#a4dbec",
      "status-info-solid": "#1c87ab",
      "control-sm": "1.75rem",
      "control-md": "2.25rem",
      "control-lg": "2.75rem",
      "inset-sm": "0.5rem",
      "inset-md": "0.75rem",
      "inset-lg": "1rem",
      "gap-sm": "0.375rem",
      "gap-md": "0.5rem",
      "gap-lg": "0.75rem"
    },
    "dark": {
      "surface-sunken": "#0b0c0f",
      "surface-base": "#14161b",
      "surface-raised": "#1d2026",
      "surface-overlay": "#2b2f38",
      "text-primary": "#eceef2",
      "text-secondary": "#9aa1ad",
      "text-muted": "#6e7683",
      "text-inverse": "#14161b",
      "interactive-idle": "#5c88f0",
      "interactive-hover": "#8badf7",
      "interactive-active": "#b6cdfb",
      "interactive-selected": "#162c6e",
      "accent": "#f0a03a",
      "accent-strong": "#f6bf6b",
      "accent-soft": "#3d1c08",
      "border-subtle": "#2b2f38",
      "border-strong": "#3e434e",
      "focus-ring-color": "#5c88f0",
      "focus-glow": "0 0 0 3px color-mix(in srgb, var(--an-focus-ring-color) 28%, transparent)",
      "focus-glow-danger": "0 0 0 3px color-mix(in srgb, var(--an-status-danger-solid) 28%, transparent)",
      "brand-gradient": "linear-gradient(135deg, var(--an-color-cobalt-500), var(--an-color-cobalt-700))",
      "accent-gradient": "linear-gradient(135deg, var(--an-color-ember-400), var(--an-color-ember-600))",
      "backdrop": "rgba(11, 12, 15, 0.6)",
      "status-success-fg": "#41b273",
      "status-success-bg": "#082517",
      "status-success-border": "#124d2e",
      "status-warn-fg": "#eaa823",
      "status-warn-bg": "#332006",
      "status-warn-border": "#6a400e",
      "status-danger-fg": "#e05e53",
      "status-danger-bg": "#380e0c",
      "status-danger-border": "#711d18",
      "status-info-fg": "#38a5c8",
      "status-info-bg": "#08222c",
      "status-info-border": "#114559"
    },
    "compact": {
      "control-sm": "1.5rem",
      "control-md": "2rem",
      "control-lg": "2.5rem",
      "inset-sm": "0.375rem",
      "inset-md": "0.5rem",
      "inset-lg": "0.75rem",
      "gap-sm": "0.25rem",
      "gap-md": "0.375rem",
      "gap-lg": "0.5rem"
    }
  },
  "component": {
    "dialog-width-sm": "26rem",
    "dialog-width-md": "36rem",
    "dialog-width-lg": "48rem",
    "drawer-width": "20rem"
  }
} as const;

export type AnvilTokens = typeof anvilTokens;

/** CSS custom property name for a primitive token path, e.g. cssVar("color.cobalt.500") -> "--an-color-cobalt-500". */
export function cssVar(path: string): string {
  return `--an-${path.replaceAll(".", "-")}`;
}
