// Anvil living styleguide. Built into a self-contained HTML page by
// scripts/make-styleguide.mjs (repo root); review artifact for each D phase.
import type { ReactElement } from "react";
import { useState } from "react";
import { Badge } from "../components/Badge.js";
import { Switch } from "../components/Switch.js";
import { ComponentsSection } from "./ComponentsSection.js";
import { DoDontSection } from "./DoDontSection.js";
import { TokensSection } from "./TokensSection.js";

export default function App(): ReactElement {
  const [dark, setDark] = useState(false);
  const [compact, setCompact] = useState(false);

  return (
    <div
      className="anvil"
      data-theme={dark ? "dark" : undefined}
      data-density={compact ? "compact" : undefined}
      style={{ minHeight: "100vh" }}
    >
      <div
        style={{
          maxWidth: "68rem",
          margin: "0 auto",
          padding: "var(--an-space-40) var(--an-space-24) var(--an-space-64)",
        }}
      >
        <header
          style={{
            display: "flex",
            flexWrap: "wrap",
            alignItems: "flex-start",
            gap: "var(--an-space-24)",
            justifyContent: "space-between",
          }}
        >
          <div>
            <h1
              style={{
                margin: 0,
                fontSize: "var(--an-font-size-28)",
                lineHeight: "var(--an-font-line-28)",
                fontWeight: 600,
              }}
            >
              Anvil
              <span
                style={{
                  display: "inline-block",
                  width: "0.5em",
                  height: "0.5em",
                  marginLeft: "0.35em",
                  borderRadius: "var(--an-radius-xs)",
                  background: "var(--an-accent)",
                }}
                aria-hidden
              />
            </h1>
            <p
              style={{
                margin: "var(--an-space-8) 0 0",
                maxWidth: "36rem",
                color: "var(--an-text-secondary)",
              }}
            >
              The surface Forge tools are shaped on. Industrial precision
              without noise: Inter + JetBrains Mono, deep cobalt with a
              restrained ember accent, crisp layered depth, decisive 120-200ms
              motion. Anvil skins app chrome only; learner course content stays
              author-themed.
            </p>
            <div style={{ display: "flex", gap: "var(--an-space-8)", marginTop: "var(--an-space-12)" }}>
              <Badge tone="primary">--an-* tokens</Badge>
              <Badge>Inter / JetBrains Mono</Badge>
              <Badge mono>@forge/ui 0.1.0</Badge>
            </div>
          </div>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              gap: "var(--an-space-8)",
              background: "var(--an-surface-raised)",
              borderRadius: "var(--an-radius-lg)",
              boxShadow: "var(--an-elevation-2)",
              padding: "var(--an-space-12) var(--an-space-16)",
            }}
          >
            <label style={{ display: "flex", alignItems: "center", gap: "var(--an-space-8)", fontSize: "var(--an-font-size-13)" }}>
              <Switch checked={dark} onCheckedChange={setDark} aria-label="Dark mode" />
              Dark mode <code style={{ fontFamily: "var(--an-font-family-mono)", fontSize: "var(--an-font-size-11)", color: "var(--an-text-muted)" }}>data-theme</code>
            </label>
            <label style={{ display: "flex", alignItems: "center", gap: "var(--an-space-8)", fontSize: "var(--an-font-size-13)" }}>
              <Switch checked={compact} onCheckedChange={setCompact} aria-label="Compact density" />
              Compact <code style={{ fontFamily: "var(--an-font-family-mono)", fontSize: "var(--an-font-size-11)", color: "var(--an-text-muted)" }}>data-density</code>
            </label>
          </div>
        </header>

        <TokensSection />
        <ComponentsSection />
        <DoDontSection />

        <footer
          style={{
            marginTop: "var(--an-space-64)",
            paddingTop: "var(--an-space-16)",
            borderTop: "1px solid var(--an-border-subtle)",
            color: "var(--an-text-muted)",
            fontSize: "var(--an-font-size-12)",
          }}
        >
          Generated by scripts/make-styleguide.mjs from @forge/ui. Tokens:
          src/tokens/anvil.tokens.json. Docs: docs/design-system/.
        </footer>
      </div>
    </div>
  );
}
